name: docs_building
channels:
  - conda-forge
dependencies:
  - python=3.14
  - setuptools >=81,<=81
  - myst-parser
  - sphinx
  - sphinx-rtd-theme
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-tabs
